[0;33m--- idf_monitor on /dev/ttyUSB0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081070: call_start_cpu1 at /home/ape/documents/programs/esp-idf/components/esp_system/port/cpu_start.c:170
[0m
[0;33m0x400d88bb: task_wdt_timeout_handling at /home/ape/documents/programs/esp-idf/components/esp_system/task_wdt/task_wdt.c:461 (discriminator 3)
[0m
[0;33m0x400d8a42: task_wdt_isr at /home/ape/documents/programs/esp-idf/components/esp_system/task_wdt/task_wdt.c:585
[0m
[0;33m0x40082f85: _xt_lowint1 at /home/ape/documents/programs/esp-idf/components/xtensa/xtensa_vectors.S:1236
[0m
[0;33m0x400d54d5: app_main at /home/ape/documents/code/esp32/robomaster/main/robomaster.c:16 (discriminator 1)
[0m
[0;33m0x400e5c14: main_task at /home/ape/documents/programs/esp-idf/components/freertos/app_startup.c:208 (discriminator 13)
[0m
[0;33m0x40087f6d: vPortTaskWrapper at /home/ape/documents/programs/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:162
[0m
Exception in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ape/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/ape/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/ape/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self.set_closing_wait(delay_sec=1)
  File "/home/ape/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 128, in set_closing_wait
    fcntl.ioctl(self.serial.fd, termios.TIOCSSERIAL, buf)
PermissionError: [Errno 1] Operation not permitted
[0m
